{% set version = "1.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mvord
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mvord_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mvord/mvord_{{ version }}.tar.gz
  sha256: 98f9331662d846381338bf6e7be1e5a65d61c6a3d9b8cfddb59daf989d17b5bb

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bb
    - r-dfoptim
    - r-mass
    - r-matrix
    - r-minqa
    - r-mnormt
    - r-mvtnorm
    - r-numderiv
    - r-optimx
    - r-pbivnorm
    - r-ucminf
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bb
    - r-dfoptim
    - r-mass
    - r-matrix
    - r-minqa
    - r-mnormt
    - r-mvtnorm
    - r-numderiv
    - r-optimx
    - r-pbivnorm
    - r-ucminf

test:
  commands:
    - $R -e "library('mvord')"           # [not win]
    - "\"%R%\" -e \"library('mvord')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mvord
  license: GPL-3.0-only
  summary: A flexible framework for fitting multivariate ordinal regression models with composite likelihood methods. Methodological details are given in Hirk, Hornik, Vana (2020) <doi:10.18637/jss.v093.i04>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
